<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ZSCHN01LP0090" failures="1" tests="6" name="Default test" time="15.244" errors="0" timestamp="2024-02-19T15:11:08 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.875"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.685"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.85"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.225">
    <failure type="java.lang.AssertionError" message="expected [Testing in] but found [Testing in IT]">
      <![CDATA[java.lang.AssertionError: expected [Testing in] but found [Testing in IT]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.OrderStepDef.should_display_the_new_article_title(OrderStepDef.java:109)
at âœ½.Should display the new Article Title(file:///D:/workspace/ConduitFinalCaseStudy/src/test/resources/features/ArticlePage.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.603"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.375"/>
</testsuite> <!-- Default test -->
